### ISSUE TITLE
Install Steps for Local Development

### ISSUE THREAD

**Issue by grayghostvisuals** [Modernizr/v3.modernizr.com#2]
@stucox  Can u describe the steps in detail to run this locally? I appreciate the help on twitter, but I'm missing something in all this still. Need directions like… step 1: do this. step 2: do this …etc. Thanks :beer:

**Comment by stucox** [comment]
Hi @grayghostvisuals, this should do it:

```
git clone --recursive git@github.com:Modernizr/v3.modernizr.com.git
cd v3.modernizr.com
./generate-meta
jekyll serve --watch
```

Bear in mind this repo’s in something of a transitional state, so things will probably change, especially seeing that there are [plans to change the API](https://github.com/Modernizr/Modernizr/pull/1184) in the main Modernizr repo.

Plus we do things in a pretty convoluted way in this repo, because we have things like legacy URLs to maintain, a fairly dated UI to support etc (and we’re in the process of redesigning the whole site anyway)… hopefully we’ll be able to simplify it with time.

**Comment by grayghostvisuals** [comment]
No Dice.

``` bash
grayghostvisuals ✭ GrayGhostVisualsMacBookAir.local  ~/Sites
$ git clone --recursive git@github.com:Modernizr/v3.modernizr.com.git
Cloning into 'v3.modernizr.com'...
remote: Reusing existing pack: 1325, done.
remote: Total 1325 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1325/1325), 1.32 MiB | 711.00 KiB/s, done.
Resolving deltas: 100% (755/755), done.
Checking connectivity... done.
Submodule 'i/js/modernizr-git' (git://github.com/Modernizr/Modernizr.git) registered for path 'i/js/modernizr-git'
Cloning into 'i/js/modernizr-git'...
remote: Reusing existing pack: 14096, done.
remote: Counting objects: 66, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 14162 (delta 14), reused 13 (delta 5)
Receiving objects: 100% (14162/14162), 12.88 MiB | 532.00 KiB/s, done.
Resolving deltas: 100% (6368/6368), done.
Checking connectivity... done.
Submodule path 'i/js/modernizr-git': checked out '079660e1a908845f82409c12787f193cf0268b9c'
$ cd v3.modernizr.com
grayghostvisuals ✭ GrayGhostVisualsMacBookAir.local  ~/Sites/v3.modernizr.com on gh-pages
$ ./generate-meta
-bash: ./generate-meta: No such file or directory
grayghostvisuals ✭ GrayGhostVisualsMacBookAir.local  ~/Sites/v3.modernizr.com on gh-pages
$ jekyll serve --watch
-bash: jekyll: command not found
```

**Comment by stucox** [comment]
Ah, you need Jekyll installed (that’s the one thing which _is_ in the README!): http://jekyllrb.com/docs/installation/

Should be as simple as this if you have Ruby installed (which you should do on a Macbook):

```
gem install jekyll
```

**Comment by grayghostvisuals** [comment]
Actually the site is using an older version of Ruby. Here's what I just got ([http://codeshare.io/Ayhl1](http://codeshare.io/Ayhl1)). Also looks like markdown is still using Maruku which is deprecated and since replaced with Kramdown.

**Comment by SlexAxton** [comment]
My guess is that you'll want to do:

``` sh
gem install bundler
bundle install
bundle exec jekyll serve --watch
```

Bundler locks in the dependency version for you.

**Comment by grayghostvisuals** [comment]
Thanks to you both, but there's a bit of confusion

I use rvm and bundler quite a bit and both help me isolate not only the ruby version, but also isolate gemsets. In this case it's nothing to do with the bundler command or bundle exec. The version of Ruby being used and markdown compiler are both outdated and as far as I can see going back to ruby-2.0.0-p247 it needs a much older version of Ruby to run. Ruby is now at 2.1.2 and markdown for Jekyll is using Kramdown not Maruku. I'm very curious where you all are at in terms of Ruby version being used.

``` bash
grayghostvisuals ✭ GrayGhostVisualsMacBookAir.local  ~/Sites/v3.modernizr.com on gh-pages
$ gemsetmk modernizr
ruby-2.0.0-p247 - #gemset created /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr
ruby-2.0.0-p247 - #generating modernizr wrappers.........
grayghostvisuals ✭ GrayGhostVisualsMacBookAir.local  ~/Sites/v3.modernizr.com on gh-pages
$ gemsetuse modernizr
Using ruby-2.0.0-p247 with gemset modernizr
grayghostvisuals ✭ GrayGhostVisualsMacBookAir.local  ~/Sites/v3.modernizr.com on gh-pages
$
grayghostvisuals ✭ GrayGhostVisualsMacBookAir.local  ~/Sites/v3.modernizr.com on gh-pages
$ bundle install
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
Fetching gem metadata from http://rubygems.org/.......
Fetching gem metadata from http://rubygems.org/..
Installing posix-spawn (0.3.6)
Installing albino (1.3.3)
Installing fast-stemmer (1.0.0)
Installing classifier (1.3.3)
Installing directory_watcher (1.4.1)
Installing kramdown (0.13.5)
Installing liquid (2.3.0)
Installing syntax (1.0.0)
Installing maruku (0.6.0)
Installing jekyll (0.11.2)
Installing rdiscount (1.6.8)
Using bundler (1.3.5)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
grayghostvisuals ✭ GrayGhostVisualsMacBookAir.local  ~/Sites/v3.modernizr.com on gh-pages
$ bundle exec jekyll serve --watch
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
/Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/gems/maruku-0.6.0/lib/maruku/input/parse_doc.rb:22:in `require': cannot load such file -- iconv (LoadError)
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/gems/maruku-0.6.0/lib/maruku/input/parse_doc.rb:22:in `<top (required)>'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/gems/maruku-0.6.0/lib/maruku.rb:85:in `require'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/gems/maruku-0.6.0/lib/maruku.rb:85:in `<top (required)>'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/gems/jekyll-0.11.2/lib/jekyll.rb:26:in `require'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/gems/jekyll-0.11.2/lib/jekyll.rb:26:in `<top (required)>'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/gems/jekyll-0.11.2/bin/jekyll:20:in `require'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/gems/jekyll-0.11.2/bin/jekyll:20:in `<top (required)>'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/bin/jekyll:23:in `load'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/bin/jekyll:23:in `<main>'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/bin/ruby_executable_hooks:15:in `eval'
    from /Users/grayghostvisuals/.rvm/gems/ruby-2.0.0-p247@modernizr/bin/ruby_executable_hooks:15:in `<main>'
```
